spring.application.name=orders
server.port=8080

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

jwt.access-token-expiration=900
jwt.refresh-token-expiration=604800

storage.bucket=restaurant-order-system
storage.region=us-east-1
storage.presigned-url-expiration=600
storage.path-style-access-enabled=true
